version: '3.8'

services:
  app:
    image: venediktovkirill/spring-boot-university
    build:
      context: .
    container_name: app
    depends_on:
      - postgres
    environment:
      - URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    ports:
      - "8080:8080"
  postgres:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./src/main/resources/static/UserAndDBCreationScrypt.sql:/docker-entrypoint-initdb.d/UserAndDBCreationScrypt.sql
    ports:
      - "5432:5432"
